#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
numlockx on &

#redshift &

xsetroot -cursor_name left_ptr

compton --config /home/tony/.config/compton/compton.conf &
wmname LG3D & # fix for some Java apps

#Polybar
~/.config/polybar/launch.sh &

flameshot &

# rofi greenclipboard daemon
greenclip daemon &

/usr/bin/lxqt-policykit-agent &

#background
feh --bg-fill /home/tony/.local/share/wallpapers/fondo3.jpg &

bspc config pointer_modifier mod1 

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor HDMI1 -d I II III IV V 

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true

bspc config focused_border_color "#7f59c6" 
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

