#!/bin/sh

#  _                                                  
# | |                                                 
# | |__   ___  _ __  __      __ _ __ ___   _ __   ___ 
# | '_ \ / __|| '_ \ \ \ /\ / /| '_ ` _ \ | '__| / __|
# | |_) |\__ \| |_) | \ V  V / | | | | | || |   | (__ 
# |_.__/ |___/| .__/   \_/\_/  |_| |_| |_||_|    \___|
#             | |                                     
#             |_|                                     
#
#-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr

# fix for some Java apps
wmname LG3D &

# Polybar launch
~/.config/polybar/launch.sh &

# Tool to take screenshots
flameshot &

# Tool to clipboard with rofi
greenclip daemon &

# Polkit
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Wallpaper
feh --bg-scale /home/antonio/.local/share/wallpapers/planeta.jpg &

bspc config pointer_modifier mod1 

# Desktops config for two monitors
bspc monitor -d I II III IV 
bspc monitor HDMI1 -d V VI VII

bspc config border_width          1
bspc config window_gap            10
bspc config border_radius         100
bspc config automatic_scheme      alternate
bspc config split_ratio           0.50
bspc config borderless_monocle    true

bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config gapless_monocle      true

# Resolution config for second monitor
if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
 xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of eDP1 
fi



