#!/bin/sh

#  _                                                  
# | |                                                 
# | |__   ___  _ __  __      __ _ __ ___   _ __   ___ 
# | '_ \ / __|| '_ \ \ \ /\ / /| '_ ` _ \ | '__| / __|
# | |_) |\__ \| |_) | \ V  V / | | | | | || |   | (__ 
# |_.__/ |___/| .__/   \_/\_/  |_| |_| |_||_|    \___|
#             | |                                     
#             |_|                                     
#
#-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_


pgrep -x sxhkd > /dev/null || sxhkd &
numlockx on &

#redshift &

xsetroot -cursor_name left_ptr

# picom --config /home/tony/.config/picom/picom.conf &
compton --config /home/tony/.config/compton/compton.conf &
wmname LG3D & # fix for some Java apps
#Polybar  
~/.config/polybar/launch.sh &

#Screenshots
flameshot &

# rofi greenclipboard daemon
greenclip daemon &

/usr/bin/lxqt-policykit-agent &

#background
feh --bg-fill /home/tony/.local/share/wallpapers/fondoPrincipal.jpg &
# feh --bg-fill /home/tony/.local/share/wallpapers/wallpaper.jpg &


bspc config pointer_modifier mod1 

bspc monitor -d I II III IV V VI 
bspc monitor HDMI1 -d IX X

bspc config border_width         2
# bspc config window_gap           6

bspc config automatic_scheme     alternate
bspc config split_ratio          0.50
bspc config borderless_monocle   true

bspc config focused_border_color "#C8C8C8" 
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

